name: Link Checker

on:
  schedule:
    # Run every Sunday at midnight
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: --accept=200,204,429 --timeout=10 --max-retries=3 --exclude ".*twitter\.com.*" --exclude ".*t\.me.*" "**/*.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Broken links detected 🔗
          content-filepath: ./lychee/out.md
          labels: report, automated issue
