name: Markdown Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v14
        with:
          globs: '**/*.md'
